### ISSUE TITLE
Whitelisting people to command the bot

### ISSUE THREAD

**Issue by bezo97** [Esherymack/Truth-Servitor#2]
Currently anyone can call the bot's commands (like ?shutdown ?status).
We could solve this problem by implementing a whitelist of people who can call certain commands.
Example usage to modify the whitelist:
- ?op bezo97
- ?deop bezo97
This will prevent people from abusing the commands.

**Comment by Esherymack** [comment]
The issue has been fixed via Discord.py's built-in check `@discord.ext.commands.has_role()`. See the documentation for this check [here](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.has_role). Presently, the users that can shut down Fortune/change his status must have the role "Botmaster." If they do not, then the command will simply not be carried out.
